### ISSUE TITLE
Differences between xsd and documentation on required fields

### ISSUE THREAD

**Issue by cedrtheb** [powsybl/powsybl.github.io#99]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Some fields are required in iidm xsd but optional in the doc

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
One example :
http://www.powsybl.org/docs/iidm/model/substation.html
The country is optional here.

In the xsd:
`<xs:attribute name="country" use="required" type="iidm:nonEmptyString"/>`

* **What is the expected behavior?**
Consistency

**Comment by mathbagu** [comment]
Since powsybl 2.5.0, countries are Optional. The information from the website is compliant with the latest version of powsybl.
